# Fastlane requirements
fastlane_version "1.109.0"

import "./../Submodules/WeTransfer-iOS-CI/Fastlane/testing_lanes.rb"
import "./../Submodules/WeTransfer-iOS-CI/Fastlane/shared_lanes.rb"

desc "Run the tests and prepare for Danger"
lane :test do |options|
    test_package(
      package_name: 'WeScan',
      package_path: ENV['PWD'],
      disable_automatic_package_resolution: false,
      device: "iPhone 14 Pro"
    )
end
